#!/bin/bash
#
# Embeds HummingbirdWatch.app (the watchOS companion app, which itself embeds
# HummingbirdWatchWidget.appex) inside the built Hummingbird.app, so a device
# install / archive actually ships a watch binary.
#
# WHY THIS ISN'T A PLAIN XCODEGEN `dependencies: [{target: HummingbirdWatch,
# embed: true}]`: XcodeGen happily generates the native "Embed Watch Content"
# Copy Files build phase (dstSubfolderSpec 16, or 13 on Xcode 26 — see below)
# plus a PBXTargetDependency, and that graph builds and embeds correctly under
# a plain `xcodebuild build -destination '...'` invocation (Xcode resolves
# each target's own SDK). It falls apart, however, the moment `-sdk
# iphonesimulator` is passed explicitly on the command line (as this repo's
# baseline CI/test command does) — `-sdk` is a command-line override that
# forces SDKROOT to iphonesimulator for *every* target participating in the
# build graph, including nested watchOS-only targets, so
# HummingbirdWatchWidget's watchOS-only APIs (e.g. WidgetFamily
# .accessoryCorner) fail to compile under the iOS SDK. There is no
# `platformFilter` (XcodeGen's is Mac-Catalyst-only: iOS/macOS/all) or
# project.yml knob that changes this — it's an xcodebuild-level limitation of
# the `-sdk` override, not a project configuration bug. Two earlier XcodeGen
# attempts hit exactly this failure (see RELEASE.md history).
#
# The fix here sidesteps the shared-build-graph problem entirely: HummingbirdWatch
# is *not* declared as an Xcode target dependency of Hummingbird at all, so
# `xcodebuild build -scheme Hummingbird -sdk iphonesimulator ...` never touches
# it. Instead, this Run Script build phase on the Hummingbird target performs
# the embed by hand, in a separate nested `xcodebuild` invocation that always
# requests the correct watchOS SDK regardless of what SDK the outer build was
# invoked with. It only does real work for device/archive builds
# (PLATFORM_NAME=iphoneos) — the Watch companion has no meaning for an iOS
# Simulator build (Watch Simulator pairing is a separate, independent flow),
# so simulator builds (and therefore the whole unit/UI test baseline) are
# entirely unaffected — this script no-ops for them.
#
# Destination is Watch/HummingbirdWatch.app up through Xcode 25, but Xcode 26
# validates companion watch apps at PlugIns/HummingbirdWatch.app instead (see
# https://github.com/yonaskolb/XcodeGen/issues/1613) — this script targets the
# Xcode 26 convention since that's what ships in this environment.

set -euo pipefail

if [ "${PLATFORM_NAME:-}" != "iphoneos" ]; then
  echo "embed_watch_content.sh: skipping (PLATFORM_NAME=${PLATFORM_NAME:-unset}) — Watch content only embeds for iphoneos device/archive builds."
  exit 0
fi

WATCH_APP_NAME="HummingbirdWatch.app"
EMBED_DERIVED_DATA="${BUILD_DIR}/EmbedWatchDerivedData"
WATCH_PRODUCTS_DIR="${EMBED_DERIVED_DATA}/Build/Products/${CONFIGURATION}-watchos"
DEST_DIR="${CODESIGNING_FOLDER_PATH}/PlugIns"
DEST_PATH="${DEST_DIR}/${WATCH_APP_NAME}"

echo "embed_watch_content.sh: building ${WATCH_APP_NAME} for watchos (${CONFIGURATION})"

# Built via its own scheme (not -target) with a dedicated -derivedDataPath —
# a bare `-target HummingbirdWatch` invocation confused Xcode's SwiftUI
# preview-injection ("Debug Dylib") support into naming its per-target
# preview dylib after the *project* rather than the target, colliding
# between HummingbirdWatch and HummingbirdWatchWidget ("Multiple commands
# produce .../Hummingbird.app/__preview.dylib"). Building via the
# (XcodeGen-autogenerated) HummingbirdWatch scheme avoids that, and a
# separate derived data path keeps this nested build from contending with
# the outer build's own DerivedData.
xcodebuild build \
  -project "${PROJECT_FILE_PATH}" \
  -scheme HummingbirdWatch \
  -sdk watchos \
  -configuration "${CONFIGURATION}" \
  -derivedDataPath "${EMBED_DERIVED_DATA}" \
  CODE_SIGNING_ALLOWED="${CODE_SIGNING_ALLOWED:-YES}" \
  ONLY_ACTIVE_ARCH=NO \
  ENABLE_PREVIEWS=NO

if [ ! -d "${WATCH_PRODUCTS_DIR}/${WATCH_APP_NAME}" ]; then
  echo "error: embed_watch_content.sh: expected ${WATCH_PRODUCTS_DIR}/${WATCH_APP_NAME} to exist after building HummingbirdWatch" >&2
  exit 1
fi

echo "embed_watch_content.sh: copying into ${DEST_PATH}"
mkdir -p "${DEST_DIR}"
rm -rf "${DEST_PATH}"
ditto "${WATCH_PRODUCTS_DIR}/${WATCH_APP_NAME}" "${DEST_PATH}"

if [ "${CODE_SIGNING_ALLOWED:-YES}" != "NO" ] && [ -n "${EXPANDED_CODE_SIGN_IDENTITY:-}" ]; then
  echo "embed_watch_content.sh: re-signing embedded ${WATCH_APP_NAME} with ${EXPANDED_CODE_SIGN_IDENTITY}"
  codesign --force --deep --sign "${EXPANDED_CODE_SIGN_IDENTITY}" "${DEST_PATH}"
fi

echo "embed_watch_content.sh: done"
